version: '3.4'

services:
  saferebus-service-1: &saferebus-service
    image: saferebus.service
    build:
      context: .
      dockerfile: SafeRebus/Services/SafeRebus.Service/Dockerfile
    env_file:
      - test.env
    networks:
      - backend_network

  saferebus-service-2:
    <<: *saferebus-service
    environment:
      - SPAM_WITH_DUMMY_REQUESTS=true
      - USE_JOKER_EXCEPTIONS=true

networks:
  backend_network:
    external: true
